# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(max_length=20, verbose_name='类别'),
        ),
    ]
