# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=40, verbose_name='电子邮箱')),
                ('urecipient', models.CharField(default='', max_length=20, verbose_name='收件人')),
                ('uaddress', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('uzip', models.CharField(default='', max_length=6, verbose_name='邮编')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='手机')),
            ],
        ),
    ]
